POST http://localhost:4000/rider/post
Content-Type: application/json

{
        "VehicleNumber":"558568646789",
        "SourcePlace":"dELHI",
        "DestinationPlace":"Bhopal",
        "typeOfTrip":"gdh",
        "dateOfTrip":"2",
        "timeOfTrip":"412-5-5",
        "availableSeat":"5",
        "PhoneNumber":"+918840099604",
        "IsRider":true
          
}
###
GET http://localhost:4000/rider/get
Content-Type: application/json
###
GET  http://localhost:4000/rider/getemail/9874562@gmail.com
Content-Type: application/json
###