###
POST http://localhost:4000/passenger
Content-Type: application/json

{
    "FullName": "Ayush2 Kumar",
    "Email":"ayush2324@gmail.com",
    "Gender":"male",
    "SourcePlace": "Lanka",
    "DestinationPlace": "Ayodhya",
    "typeOfTrip": "One-way",
    "dateOfTrip": "2022-01-22",
    "timeOfTrip": "12:34",
    "PhoneNumber": "8840099654",
    "Rating":5,
    "Price":100,
    "Distance":"800KM",
    "IsRider": false  
}
###vfdxxd
GET http://localhost:4000/passenger/get
Content-Type: application/json
###
GET  http://localhost:4000/passenger/get/65d974e31eb963421af40dc9
Content-Type: application/json
###
GET  http://localhost:4000/passenger/getemail/ayush@gmail.com
Content-Type: application/json

###
GET  http://localhost:4000/passenger/approval/ayushayushravi@gmail.com
Content-Type: application/json

###
PUT http://localhost:4000/passenger/update/ayushayushravi@gmail.com
Content-Type: application/json

{
    
    "RiderEmail":"9451@gamail.com"
}