###
POST http://localhost:4000/passenger
Content-Type: application/json

{
    "FullName": "Sham",
    "Email":"ayush@gmail.com",
    "Gender":"male",
    "SourcePlace": "Bombay",
    "DestinationPlace": "Goa",
    "typeOfTrip": "One-way",
    "dateOfTrip": "2024-02-25",
    "timeOfTrip": "09:00",
    "PhoneNumber": "8840099604",
    "Rating":5,
    "Price":2500,
    "Distance":"100KM",
    "IsRider": true  
}