GET http://localhost:4000/tripdet/getpath
Content-Type: application/json

{    
          "SourcePlace":"Mumbai",
          "DestinationPlace":"Goa",
          "dateOfTrip":"09-02-2024"
}

###
GET http://localhost:4000/tripdet
Content-Type: application/json

###
POST http://localhost:4000/tripdet
Content-Type: application/json

{
    "Name": "Ayush",
    "VehicleNumber": "UP70AZ3501",
    "VehicleName":"Balero",
    "VehicleColour":"Blue ",
    "SourcePlace": "Kanpur",
    "DestinationPlace": "Delhi",
    "typeOfTrip": "One-way",
    "dateOfTrip": "2024-02-01",
    "timeOfTrip": "09:00",
    "availableSeat": "2",
    "PhoneNumber": "8840066851",
    "Rating":5,
    "Price":8000,
    "Distance":"1500KM",
    "IsRider": true  

}
###
GET  http://localhost:4000/tripdet/get/65d974e31eb963421af40dc9
Content-Type: application/json
###